app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Careful when adding forward slash on routes


Route::group( ['prefix' => 'admin', 'middleware' => 'auth'], function() {

    //AJAX Routes
    Route::post('ajax/upload-user-image', 'Admin\AjaxController@UploadUserImage');
    Route::get('ajax/upload-user-image', 'Admin\AjaxController@UploadUserImage');
    Route::post('ajax/delete-user-image', 'Admin\AjaxController@DeleteUserImage');

    // User Routes
    Route::get('profile', 'Admin\UsersController@profile');
    Route::post('profile', 'Admin\UsersController@saveProfile');
    Route::get('users/search', 'Admin\UsersController@search');
    Route::resource('users', 'Admin\UsersController');

    // Pages Routes
    Route::get('pages/search', 'Admin\PagesController@search');
    Route::resource('pages', 'Admin\PagesController');

    // Post Routes
    Route::get('posts/search', 'Admin\PostsController@search');
    Route::resource('posts', 'Admin\PostsController');

    // Post Categories
    Route::get('post-categories/search', 'Admin\PostCategoriesController@search');
    Route::resource('post-categories', 'Admin\PostCategoriesController');

    // Controller routes should be placed here
    Route::controllers([
        'settings' => 'Admin\SettingsController',
        '/' => 'Admin\AdminController'
    ]);



});

Route::controllers([
    'auth' => 'Auth\AuthenticateController',
    'password' => 'Auth\PasswordController',
]);

// Front page
Route::get('register', 'PageController@register');
Route::post('register', 'PageController@postRegister');

Route::any('{url?}', ['uses' => 'PageController@index'])->where(['url' => '[-a-z0-9/]+']);

app/Models/Posts.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Posts extends Model {

	//
    protected $appends = array('parent_page');

    public static function generateSlug( $pagename, $page_type = 'post' ) {

        $slug = Str::slug( $pagename );
        $slugs = Self::whereRaw("url_slug REGEXP '^{$slug}(-[0-9]*)?$'")->where('post_type', '=', $page_type, 'AND');

        if ($slugs->count() === 0) {
            return $slug;
        }

        // Get the last matching slug
        $lastSlug = $slugs->orderBy('url_slug', 'desc')->first()->slug;

        // Strip the number off of the last slug, if any
        $lastSlugNumber = intval(str_replace($slug . '-', '', $lastSlug));

        // Increment/append the counter and return the slug we generated
        return $slug . '-' . ($lastSlugNumber + 1);
    }

    public function getParentNameAttribute(){
        $parent = $this->parent()->get()->first();
        return !empty($parent) ? $parent->title : '';
    }

    public function getCategoryNameAttribute(){
        $parent = $this->parentCategory()->get()->first();
        return !empty($parent) ? $parent->name : '';
    }

    public function children(){
        return $this->hasMany('App\Models\Posts', 'parent_id', 'id');
    }

    public function parent(){
        return $this->belongsTo('App\Models\Posts', 'parent_id', 'id');
    }

    public function parentCategory(){
        return $this->belongsTo('App\Models\Categories', 'category_id', 'id');
    }

    public function getUrlPathAttribute(){
        $page = Self::where('url_slug', $this->attributes['url_slug'])->get()->first();
        return $this->_buildPageURL($page);

    }

    private function _traverseBuildParentHeirarchy($model){
        if( !empty($model) ) {
            $item['model'] = $model;
            $parent = $model->parent()->get()->first();

            if ( !empty($parent) && $parent->count() > 0) {
                $item['parent'] = $this->_traverseBuildParentHeirarchy($parent);
            }

            $parents[] = $item;
            return $parents;
        }

    }

    private function _traverseHeirarchyToURL($array ){

        foreach($array as $a){
            $url = $a['model']->url_slug . '/';
            if( isset($a['parent']) )
                $url .= $this->_traverseHeirarchyToURL($a['parent']);
        }
        return $url;

    }

    private function _buildPageURL($page){
        $parent_array = $this->_traverseBuildParentHeirarchy($page);
        $url = $this->_traverseHeirarchyToURL($parent_array);
        $url = explode('/', $url);
        $url = array_reverse($url);

        $url_string = '';
        foreach($url as $u){
            if( !empty($u) )
                $url_string .=  $u . '/';
        }

        return substr($url_string, 0, -1);
    }



}

resources/views/admin/pages/pages/create.blade.php
@extends('admin/main')

@section('content')
    <div class="content-wrapper">

    <section class="content-header">
        <h1>Pages <small>Create</small></h1>
        <ol class="breadcrumb">
            <li><a href="{{ url('admin/dashboard') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="{{ url('admin/pages') }}"><i class="fa fa-file"></i> Pages</a></li>
            <li class="active">Create</li>
        </ol>
    </section>

    <section class="content">

        @include('messages/message')

        {!! Form::open( array('url' => 'admin/pages/', 'id' => 'page_edit_form' ) ) !!}

        <div class="row">

            <div class="col-xs-8">
                <div class="box">
                    <div class="box-header">
                        <h4>Page Details</h4>
                    </div>
                    <div class="box-body">

                        <div class="form-group">
                            <label for="page_title">Page Title</label>
                            <input class="form-control" type="text" id="page_title" name="page_title" value="{{ $page_name or Request::old('page_title') }}"/>
                        </div>

                        <div class="form-group">
                            <label for="parent">Parent Page</label>
                            <select name="parent" id="parent" class="form-control">
                                <option value="0"></option>
                                @if( !empty($pages) )
                                    @foreach($pages as $p)
                                        @include('admin/pages/pages/recursion/create-parent-pages', ['pages' => $p, 'ctr' => 0])
                                    @endforeach
                                @endif
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="editor">Content</label>
                            <textarea name="content" id="content" cols="30" rows="10" class="form-control">{{ $content or Request::old('content') }}</textarea>
                        </div>


                    </div>
                </div>
            </div>

            <div class="col-xs-4">
                <div class="box">
                    <div class="box-header">
                        <h4>Meta Data</h4>
                    </div>
                    <div class="box-body">

                        <div class="form-group">
                            <label for="meta_title">Meta Title</label>
                            <input class="form-control" type="text" name="meta_title" value="{{ $page_title or Request::old('meta_title')}}" id="meta_title"/>
                        </div>

                        <div class="form-group">
                            <label for="meta_desc">Meta Description</label>
                            <textarea name="meta_desc" id="meta_desc" cols="10" rows="3" class="form-control">{{ $meta_desc or Request::old('meta_desc') }}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="meta_keywords">Meta Keywords</label>
                            <textarea name="meta_keywords" id="meta_keywords" cols="10" rows="3" class="form-control">{{ $meta_keywords or Request::old('meta_keywords') }}</textarea>
                        </div>

                    </div>
                </div>
            </div>

        </div>

        <div class="row">

            <div class="col-xs-12">
            <a href="{{ url('admin/pages') }}" class="btn btn-default">Back</a>
            <input type="submit" name="save_page" value="Save" class="btn btn-primary"/>
            </div>

        </div>

        {!! Form::close() !!}

    </section>



    </div>
@endsection

@section('scripts')
    <script src="https://cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
    <script type="text/javascript">
        $(function () {
            // Replace the <textarea id="editor1"> with a CKEditor
            // instance, using default configuration.
            CKEDITOR.replace('content');
          });
    </script>
@endsection

resources/views/admin/pages/pages/edit.blade.php
@extends('admin/main')

@section('content')
    <div class="content-wrapper">

    <section class="content-header">
        <h1>Pages <small>Edit</small></h1>
        <ol class="breadcrumb">
            <li><a href="{{ url('admin/dashboard') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="{{ url('admin/pages') }}"><i class="fa fa-file"></i> Pages</a></li>
            <li class="active">Edit</li>
        </ol>
    </section>

    <section class="content">

        @include('messages/message')

        {!! Form::open( array('url' => 'admin/pages/' . $page->id , 'id' => 'page_edit_form' ) ) !!}

        <input type="hidden" name="_method" value="PUT" id="form_method" />
        <input type="hidden" name="page_id" value="{{ $page->id }}"/>

        <div class="row">
        <div class="col-xs-8">

        <div class="box">
            <div class="box-header">
                <h4>Page Details</h4>
            </div>
            <div class="box-body">

                <div class="form-group">
                    <label for="page_title">Page Title</label>
                    <input class="form-control" type="text" id="page_title" name="page_title" value="{{ $page->title }}"/>
                </div>

                <div class="form-group">
                    <label for="parent">Parent Page</label>
                    <select name="parent" id="parent" class="form-control">
                        <option value="0"></option>
                        @if( !empty($pages) )
                            @foreach($pages as $p)
                                @include('admin/pages/pages/recursion/edit-parent-pages', ['pages' => $p, 'ctr' => 0])
                            @endforeach
                        @endif
                    </select>
                </div>

                <div class="form-group">
                    <label for="editor">Content</label>
                    <textarea name="content" id="content" cols="30" rows="10" class="form-control">{{ $page->content }}</textarea>
                </div>


            </div>
        </div>
        </div>

        <div class="col-xs-4">
            <div class="box">
                <div class="box-header">
                    <h4>Meta Data</h4>
                </div>
                <div class="box-body">

                <div class="form-group">
                    <label for="meta_title">Meta Title</label>
                    <input class="form-control" type="text" name="meta_title" value="{{ $page->meta_title }}" id="meta_title"/>
                </div>

                <div class="form-group">
                    <label for="meta_desc">Meta Description</label>
                    <textarea name="meta_desc" id="meta_desc" cols="10" rows="3" class="form-control">{{ $page->meta_desc }}</textarea>
                </div>

                <div class="form-group">
                    <label for="meta_keywords">Meta Keywords</label>
                    <textarea name="meta_keywords" id="meta_keywords" cols="10" rows="3" class="form-control">{{ $page->meta_keywords }}</textarea>
                </div>


                </div>
            </div>
        </div>

        </div>

        <div class="row">

            <div class="col-xs-12">
            <a href="{{ url('admin/pages') }}" class="btn btn-default">Back</a>
            <a href="#" class="btn btn-warning del-data-entry" data-target-form="#page_edit_form">Delete</a>
            <input type="submit" name="save_user" value="Save" class="btn btn-primary"/>
            </div>

        </div>

        {!! Form::close() !!}








    </section>



    </div>
@endsection

@section('scripts')
    <script src="https://cdn.ckeditor.com/4.4.3/standard/ckeditor.js"></script>
    <script type="text/javascript">
        $(function () {
            // Replace the <textarea id="editor1"> with a CKEditor
            // instance, using default configuration.
            CKEDITOR.replace('content');
          });
    </script>
@endsection

resources/views/admin/pages/pages/index.blade.php
@extends('admin/main')
@section('content')
    <div class="content-wrapper">

    <section class="content-header">
        <h1>Pages</h1>
        <ol class="breadcrumb">
            <li><a href="{{ url('admin') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active"><i class="fa fa-file"></i> Pages</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
        <div class="col-xs-12">

            {{-- Pages Box Start --}}
            <div class="box box-primary">

                <div class="box-header">
                    <div class="row">

                    <div class="col-sm-2">
                        <a class="btn btn-block btn-primary" href="{{ url('admin/pages/create') }}">Add Page</a>
                    </div>

                    </div>
                </div>

                <div class="box-header">
                    <div class="row">
                        <div class="col-sm-6">

                            <div class="show-items form-inline">
                            {!! Form::open( array('id' => 'show_item_form', 'method' => 'get') ) !!}
                            <label>
                            Show
                            <select class="select-show-item form-control" name="show">
                                <option value="25" @if( $show == '25'){{ 'selected="selected"' }}@endif>25</option>
                                <option value="50" @if( $show == '50'){{ 'selected="selected"' }}@endif>50</option>
                                <option value="all" @if( $show == '0'){{ 'selected="selected"' }}@endif>All</option>
                            </select>

                            @if( isset($page) )
                                <input type="hidden" name="page" value="{{ $page }}"/>
                            @elseif( isset($s) )
                                <input type="hidden" name="search" value="{{ $s }}"/>
                            @endif

                            pages
                            </label>
                            {!! Form::close() !!}
                            </div>

                        </div>

                        <div class="col-sm-3 col-sm-offset-3">

                            <div class="data-search">

                            {!! Form::open(array('method' => 'get', 'url' => 'admin/pages/search')) !!}
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-search"></i></span>
                                    <input class="form-control" type="text" placeholder="Search" name="search" value="{{ $s or '' }}"/>
                                    <span class="input-group-btn">
                                        <input type="submit" class="btn btn-info btn-flat" type="button" value="Go">
                                    </span>
                                </div>
                            {!! Form::close() !!}


                            </div>

                        </div>

                    </div>
                </div>

                <div class="box-body dataTables_wrapper">

                    @include('messages/message')

                    {!! Form::open(array('url' => 'admin/pages/0', 'id' => 'all_pages_form')) !!}
                        {{-- Spoof the delete verb to access delete method see tutorial from https://scotch.io/tutorials/simple-laravel-crud-with-resource-controllers --}}
                        <input type="hidden" name="_method" value="DELETE"/>
                    <div class="row">
                    <div class="col-sm-12">
                    <table class="table table-hover table-bordered table-striped">
                        <tr>
                            <th><input type="checkbox" id="check_all_table_items" /></th>
                            <th>Title</th>
                            <th>Url Slug</th>
                            <th>Parent</th>
                            <th>Created</th>
                            <th>Actions</th>
                        </tr>

                        @if( !empty($pages) )
                        @foreach($pages as $p)
                        <tr>
                            <td><input type="checkbox" name="id[]" value="{{ $p->id }}" id="page_{{ $p->id }}" class="check-all-table-item"/></td>
                            <td><a href="{{ url($p->UrlPath) }}" target="_blank"> {{ $p->title }} </a></td>
                            <td>{{ $p->url_slug }}</td>
                            <td>{{ $p->parent_name }}</td>
                            <td>{{ $p->created_at->format('M d, Y') }}</td>
                            <td>
                                <div class="table-tools">
                                    <a href="{{ url('admin/pages/' . $p->id . '/edit') }}" title="Edit Page"><i class="fa fa-edit"></i></a>
                                    <a href="#" title="Delete Page" class="del-table-itm" data-target="#page_{{ $p->id }}" data-target-form="#all_pages_form"><i class="fa fa-trash-o"></i></a>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        @endif

                    </table>
                    </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-2">
                            <input class="btn btn-block btn-default" type="submit" name="delete" value="Delete Selected"/>
                        </div>
                        <div class="col-sm-10">
                            <div class="pagination-block">
                            {!! $pagination !!}
                            </div>
                        </div>
                    </div>

                    {!! Form::close() !!}

                </div>
            </div>
               {{-- Pages Box End--}}

        </div>
        </div>

    </section>


    </div>
    {{-- End Content Wrapper --}}
@endsection