app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Careful when adding forward slash on routes


Route::group( ['prefix' => 'admin', 'middleware' => 'auth'], function() {

    //AJAX Routes
    Route::post('ajax/upload-user-image', 'Admin\AjaxController@UploadUserImage');
    Route::get('ajax/upload-user-image', 'Admin\AjaxController@UploadUserImage');
    Route::post('ajax/delete-user-image', 'Admin\AjaxController@DeleteUserImage');

    // User Routes
    Route::get('profile', 'Admin\UsersController@profile');
    Route::post('profile', 'Admin\UsersController@saveProfile');
    Route::get('users/search', 'Admin\UsersController@search');
    Route::resource('users', 'Admin\UsersController');

    // Pages Routes
    Route::get('pages/search', 'Admin\PagesController@search');
    Route::resource('pages', 'Admin\PagesController');

    // Post Routes
    Route::get('posts/search', 'Admin\PostsController@search');
    Route::resource('posts', 'Admin\PostsController');

    // Post Categories
    Route::get('post-categories/search', 'Admin\PostCategoriesController@search');
    Route::resource('post-categories', 'Admin\PostCategoriesController');

    // Controller routes should be placed here
    Route::controllers([
        'settings' => 'Admin\SettingsController',
        '/' => 'Admin\AdminController'
    ]);



});

Route::controllers([
    'auth' => 'Auth\AuthenticateController',
    'password' => 'Auth\PasswordController',
]);

// Front page
Route::get('register', 'PageController@register');
Route::post('register', 'PageController@postRegister');

Route::any('{url?}', ['uses' => 'PageController@index'])->where(['url' => '[-a-z0-9/]+']);

app/Models/Categories.php
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Categories extends Model {

	//
    public static function generateSlug( $name ) {

        $slug = Str::slug( $name );
        $slugs = Self::whereRaw("url_slug REGEXP '^{$slug}(-[0-9]*)?$'");

        if ($slugs->count() === 0) {
            return $slug;
        }

        // Get the last matching slug
        $lastSlug = $slugs->orderBy('url_slug', 'desc')->first()->slug;

        // Strip the number off of the last slug, if any
        $lastSlugNumber = intval(str_replace($slug . '-', '', $lastSlug));

        // Increment/append the counter and return the slug we generated
        return $slug . '-' . ($lastSlugNumber + 1);
    }

    public function children(){
        return $this->hasMany('App\Models\Categories', 'parent_id', 'id');
    }

    public function getParentCategoryAttribute(){
        $parent_id = $this->attributes['parent_id'];

        if( $parent_id > 0){
            $c = Self::find($parent_id);
            return $c->name;
        }
        else{
            return '';
        }


    }

}

resources/views/admin/pages/categories/create.blade.php
@extends('admin/main')

@section('content')
    <div class="content-wrapper">

    <section class="content-header">
        <h1>Category <small>Create</small></h1>
        <ol class="breadcrumb">
            <li><a href="{{ url('admin/dashboard') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="{{ url('admin/post-categories') }}"><i class="fa fa-thumb-tack"></i> Categories</a></li>
            <li class="active">Create</li>
        </ol>
    </section>

    <section class="content">

        @include('messages/message')

        {!! Form::open( array('url' => 'admin/post-categories/', 'id' => 'category_edit_form' ) ) !!}

        <div class="row">

            <div class="col-xs-8">
                <div class="box">
                    <div class="box-header">
                        <h4>Category Details</h4>
                    </div>
                    <div class="box-body">

                        <div class="form-group">
                            <label for="name">Category Name</label>
                            <input class="form-control" type="text" name="name" id="name" value="{{ $name or Request::old('name') }}"/>
                        </div>

                        <div class="form-group">
                            <label for="parent">Category Parent</label>
                            <select name="parent" id="parent" class="form-control">
                                <option></option>
                                @if( !empty($categories) )
                                    @foreach($categories as $c)
                                        @include('admin/pages/categories/recursion/create-parent-categories', ['categories' => $c, 'ctr' => 0])
                                    @endforeach
                                @endif
                            </select>
                        </div>



                    </div>
                </div>
            </div>

            <div class="col-xs-4">
                <div class="box">
                    <div class="box-header">
                        <h4>Meta Data</h4>
                    </div>
                    <div class="box-body">

                        <div class="form-group">
                            <label for="meta_title">Meta Title</label>
                            <input class="form-control" type="text" name="meta_title" value="{{ $page_title or Request::old('meta_title')}}" id="meta_title"/>
                        </div>

                        <div class="form-group">
                            <label for="meta_desc">Meta Description</label>
                            <textarea name="meta_desc" id="meta_desc" cols="10" rows="3" class="form-control">{{ $meta_desc or Request::old('meta_desc') }}</textarea>
                        </div>

                        <div class="form-group">
                            <label for="meta_keywords">Meta Keywords</label>
                            <textarea name="meta_keywords" id="meta_keywords" cols="10" rows="3" class="form-control">{{ $meta_keywords or Request::old('meta_keywords') }}</textarea>
                        </div>

                    </div>
                </div>
            </div>

        </div>

        <div class="row">

            <div class="col-xs-12">
            <a href="{{ url('admin/post-categories') }}" class="btn btn-default">Back</a>
            <input type="submit" name="save_page" value="Save" class="btn btn-primary"/>
            </div>

        </div>

        {!! Form::close() !!}

    </section>



    </div>
@endsection

resources/views/admin/pages/categories/edit.blade.php
@extends('admin/main')

@section('content')
    <div class="content-wrapper">

    <section class="content-header">
        <h1>Category <small>Edit</small></h1>
        <ol class="breadcrumb">
            <li><a href="{{ url('admin/dashboard') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li><a href="{{ url('admin/post-categories') }}"><i class="fa fa-thumb-tack"></i> Categories</a></li>
            <li class="active">Edit</li>
        </ol>
    </section>

    <section class="content">

        @include('messages/message')

        {!! Form::open( array('url' => 'admin/post-categories/' . $category->id , 'id' => 'category_edit_form' ) ) !!}

        <input type="hidden" name="_method" value="PUT" id="form_method" />
        <input type="hidden" name="page_id" value="{{ $category->id }}"/>

        <div class="row">
        <div class="col-xs-8">

        <div class="box">
            <div class="box-header">
                <h4>Page Details</h4>
            </div>
            <div class="box-body">

                <div class="form-group">
                    <label for="name">Category Name</label>
                    <input class="form-control" type="text" id="name" name="name" value="{{ $category->name }}"/>
                </div>

                <div class="form-group">
                    <label for="parent">Parent Category</label>
                    <select name="parent" id="parent" class="form-control">
                        <option value=""></option>
                        @if( !empty($categories) )
                            @foreach($categories as $c)
                                @include('admin/pages/categories/recursion/edit-parent-categories', ['categories' => $c, 'ctr' => 0])
                            @endforeach
                        @endif
                    </select>
                </div>

            </div>
        </div>
        </div>

        <div class="col-xs-4">
            <div class="box">
                <div class="box-header">
                    <h4>Meta Data</h4>
                </div>
                <div class="box-body">

                <div class="form-group">
                    <label for="meta_title">Meta Title</label>
                    <input class="form-control" type="text" name="meta_title" value="{{ $category->meta_title }}" id="meta_title"/>
                </div>

                <div class="form-group">
                    <label for="meta_desc">Meta Description</label>
                    <textarea name="meta_desc" id="meta_desc" cols="10" rows="3" class="form-control">{{ $category->meta_desc }}</textarea>
                </div>

                <div class="form-group">
                    <label for="meta_keywords">Meta Keywords</label>
                    <textarea name="meta_keywords" id="meta_keywords" cols="10" rows="3" class="form-control">{{ $category->meta_keywords }}</textarea>
                </div>


                </div>
            </div>
        </div>

        </div>

        <div class="row">

            <div class="col-xs-12">
            <a href="{{ url('admin/post-categories') }}" class="btn btn-default">Back</a>
            <a href="#" class="btn btn-warning del-data-entry" data-target-form="#category_edit_form">Delete</a>
            <input type="submit" name="save_user" value="Save" class="btn btn-primary"/>
            </div>

        </div>

        {!! Form::close() !!}


    </section>



    </div>
@endsection

resources/views/admin/pages/categories/index.blade.php
@extends('admin/main')
@section('content')
    <div class="content-wrapper">

    <section class="content-header">
        <h1>Category</h1>
        <ol class="breadcrumb">
            <li><a href="{{ url('admin') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active"><i class="fa fa-thumb-tack"></i> Categories</li>
        </ol>
    </section>

    <section class="content">
        <div class="row">
        <div class="col-xs-12">

            {{-- Posts Box Start --}}
            <div class="box box-primary">

                <div class="box-header">
                    <div class="row">

                    <div class="col-sm-2">
                        <a class="btn btn-block btn-primary" href="{{ url('admin/post-categories/create') }}">Add Category</a>
                    </div>



                    </div>
                </div>

                <div class="box-header">
                    <div class="row">
                        <div class="col-sm-6">

                            <div class="show-items form-inline">
                            {!! Form::open( array('id' => 'show_item_form', 'method' => 'get') ) !!}
                            <label>
                            Show
                            <select class="select-show-item form-control" name="show">
                                <option value="25" @if( $show == '25'){{ 'selected="selected"' }}@endif>25</option>
                                <option value="50" @if( $show == '50'){{ 'selected="selected"' }}@endif>50</option>
                                <option value="all" @if( $show == '0'){{ 'selected="selected"' }}@endif>All</option>
                            </select>

                            @if( isset($page) )
                                <input type="hidden" name="page" value="{{ $page }}"/>
                            @elseif( isset($s) )
                                <input type="hidden" name="search" value="{{ $s }}"/>
                            @endif

                            users
                            </label>
                            {!! Form::close() !!}
                            </div>

                        </div>

                        <div class="col-sm-3 col-sm-offset-3">

                            <div class="data-search">

                            {!! Form::open(array('method' => 'get', 'url' => 'admin/post-categories/search')) !!}
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fa fa-search"></i></span>
                                    <input class="form-control" type="text" placeholder="Search" name="search" value="{{ $s or '' }}"/>
                                    <span class="input-group-btn">
                                        <input type="submit" class="btn btn-info btn-flat" type="button" value="Go">
                                    </span>
                                </div>
                            {!! Form::close() !!}


                            </div>

                        </div>

                    </div>
                </div>

                <div class="box-body dataTables_wrapper">

                    {{-- Show Success message if any --}}
                    @include('messages/message')


                    {!! Form::open(array('url' => 'admin/post-categories/0', 'id' => 'all_categories_form')) !!}
                        {{-- Spoof the delete verb to access delete method see tutorial from https://scotch.io/tutorials/simple-laravel-crud-with-resource-controllers --}}
                        <input type="hidden" name="_method" value="DELETE"/>
                    <div class="row">
                    <div class="col-sm-12">
                    <table class="table table-hover table-bordered table-striped">
                        <tr>
                            <th><input type="checkbox" id="check_all_table_items" /></th>
                            <th>Name</th>
                            <th>Url Slug</th>
                            <th>Parent Category</th>
                            <th>Created</th>
                            <th>Actions</th>
                        </tr>

                        @if( !empty($categories) )
                        @foreach($categories as $c)
                        <tr>
                            <td><input type="checkbox" name="id[]" value="{{ $c->id }}" id="category_{{ $c->id }}" class="check-all-table-item"/></td>
                            <td><a href="{{ url('admin/post-categories/' . $c->id . '/edit') }}"> {{ $c->name }} </a></td>
                            <td>{{ $c->url_slug }}</td>
                            <td>{{ $c->parent_category }}</td>
                            <td>{{ $c->created_at->format('M d, Y') }}</td>
                            <td>
                                <div class="table-tools">
                                    <a href="{{ url('admin/post-categories/' . $c->id . '/edit') }}" title="Edit Category"><i class="fa fa-edit"></i></a>
                                    <a href="#" title="Delete Category" class="del-table-itm" data-target="#category_{{ $c->id }}" data-target-form="#all_categories_form"><i class="fa fa-trash-o"></i></a>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                        @endif

                    </table>
                    </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-2">
                            <input class="btn btn-block btn-default" type="submit" name="delete" value="Delete Selected"/>
                        </div>
                        <div class="col-sm-10">
                            <div class="pagination-block">
                            {!! $pagination !!}
                            </div>
                        </div>
                    </div>

                    {!! Form::close() !!}

                </div>
            </div>
               {{-- Posts Box End--}}

        </div>
        </div>

    </section>


    </div>
{{-- End Content Wrapper --}}
@endsection